### PR TITLE
Md 1794

### PR DESCRIPTION
**Pull request by laheara143**
Access Ci Link needed to be added to header and footer
https://cyberteamportal.atlassian.net/browse/D8-1794

### CODE REVIEW

**Comment by laheara143** [comment]
Logo at footer needs to be spaced out

**Comment by laheara143** [comment]
Not ready to be merged yet.

**Comment by laheara143** [comment]
> Logo at footer needs to be spaced out

image
image

**Comment by a-pasquale** [comment]
@laheara143 the menus are not visible for anonymous people
image

**Pull request merged**
